-- DEFINE OBJECTS --

CREATE TYPE EXCHANGE_ARR AS VARRAY(5) OF VARCHAR(20)
/

-- ADDRESS --

CREATE TYPE ADDRESS_TY AS OBJECT(
    STREET_NO NUMBER(4),
    STREET_NAME VARCHAR(10),
    SUBURB VARCHAR(10),
    STATE VARCHAR(10),
    PIN NUMBER(6)
)
/

-- STOCKS --

CREATE TYPE STOCK_TY AS OBJECT(
    COMPANY CHAR(10),
    CURR_PRICE NUMBER(6,2),
    EXCHANGES EXCHANGE_ARR,
    LAST_DIV NUMBER(4,2),
    EPS NUMBER(4,2)
)
/

-- INVESTMENTS -- 

CREATE TYPE INVESTMENT_TY AS OBJECT(
    COMPANY REF STOCK_TY,
    PUR_PRICE NUMBER(6,2),
    PUR_DATE DATE,
    QTY NUMBER(5)
)
/

-- INVESTMENT NESTED TABLE TYPE --

CREATE TYPE INVESTMENT_NTTY AS TABLE OF INVESTMENT_TY
/

CREATE TYPE CLIENT_TY AS OBJECT(
    CLNO CHAR(5),
    NAME VARCHAR(20),
    ADDRESS ADDRESS_TY,
    INVESTMENTS INVESTMENT_NTTY
)
/

-- CREATE CLIENT TABLE --

CREATE TABLE CLIENTS OF CLIENT_TY(
    CONSTRAINT CLIENT_PK PRIMARY KEY(CLNO)
)NESTED TABLE INVESTMENTS STORE AS INVESTMENT_NTTB
/

-- CREATE STOCKS TABLE --

CREATE TABLE STOCKS OF STOCK_TY(
    CONSTRAINT STOCK_PK PRIMARY KEY(COMPANY)
)
/

-- CONSTRAINT TO REFERENCE OBJECTS ONLY FROM STOCKS TABLE --

ALTER TABLE INVESTMENT_NTTB
ADD SCOPE FOR (COMPANY) IS STOCKS
/


-- INSERT DATA INTO STOCKS --

INSERT INTO STOCKS VALUES('BHP', 10.50, EXCHANGE_ARR('Sydney', 'New York'), 1.50, 3.20)
/

INSERT INTO STOCKS VALUES('IBM', 70.00, EXCHANGE_ARR('London', 'New York', 'Tokyo'), 4.25, 10)
/

INSERT INTO STOCKS VALUES('INTEL', 76.50, EXCHANGE_ARR('London', 'New York'), 5.00, 12.40)
/

INSERT INTO STOCKS VALUES('FORD', 40.00, EXCHANGE_ARR('New York'), 2.00, 8.50)
/

INSERT INTO STOCKS VALUES('GM', 60.00, EXCHANGE_ARR('New York'), 2.50, 9.20)
/

INSERT INTO STOCKS VALUES('INFOSYS', 45.00, EXCHANGE_ARR('New York'), 3.00, 7.80)
/


-- INSERT DATA INTO CLIENTS TABLE --

INSERT INTO CLIENTS VALUES(
    'C001', 
    'John Smith', 
    ADDRESS_TY(36, 'East Av', 'Bentley', 'WA', 6102),
    INVESTMENT_NTTY(
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'BHP'), 12.00, '02-OCT-2001', 1000),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'BHP'), 10.50, '08-JUN-2002', 2000),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'IBM'), 58.00, '12-FEB-2000', 500),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'IBM'), 65.0, '10-APR-2001', 1200),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'INFOSYS'), 64.0, '11-AUG-2001', 1000)
    )
)
/

INSERT INTO CLIENTS VALUES(
    'C002',
    'Jil Brody',
    ADDRESS_TY(42, 'Bent St', 'Perth', 'WA', 6001),
    INVESTMENT_NTTY(
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE COMPANY = 'INTEL'), 35.00, '30-JAN-2000', 300),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE COMPANY = 'INTEL'), 54.00, '30-JAN-2001', 400),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE COMPANY = 'INTEL'), 60.00, '02-OCT-2001', 200),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE COMPANY = 'FORD'), 40.00, '05-OCT-1999', 300),
        INVESTMENT_TY((SELECT REF(S) FROM STOCKS S WHERE COMPANY = 'GM'), 55.50, '12-DEC-2000', 500)
    )
)
/

commit
/

-- Q1 --

SELECT DISTINCT C.NAME, I.COMPANY.COMPANY AS STOCK, I.COMPANY.CURR_PRICE AS CURR_PRICE, I.COMPANY.LAST_DIV AS LAST_DIV, I.COMPANY.EPS AS EPS
FROM CLIENTS C, TABLE(C.INVESTMENTS) I
/


-- Q2 --

SELECT C.NAME, I.COMPANY.COMPANY, SUM(I.QTY) TOTAL_SHARES, SUM(I.PUR_PRICE*I.QTY)/SUM(I.QTY) AVG_PRICE
FROM CLIENTS C, TABLE(C.INVESTMENTS) I
GROUP BY C.NAME, I.COMPANY.COMPANY
/


-- Q3 --

SELECT I.COMPANY.COMPANY STOCK, C.NAME CLIENT, SUM(I.QTY) QTY, SUM(I.QTY*I.COMPANY.CURR_PRICE) CURR_PRICE
FROM CLIENTS C, TABLE(C.INVESTMENTS) I
WHERE 'New York' IN (SELECT E.COLUMN_VALUE FROM TABLE(I.COMPANY.EXCHANGES) E)
GROUP BY C.NAME, I.COMPANY.COMPANY
/


--Q4 --

SELECT C.NAME, SUM(I.COMPANY.CURR_PRICE*I.QTY)
FROM CLIENTS C, TABLE(C.INVESTMENTS) I
GROUP BY C.NAME
/


-- Q5 --

SELECT C.NAME, SUM(I.PUR_PRICE*I.QTY) - SUM(I.COMPANY.CURR_PRICE*I.QTY) PROFIT
FROM CLIENTS C, TABLE(C.INVESTMENTS) I
GROUP BY C.NAME
/


-- Q4 --

-- DELETE INFOSYS STOCKS FROM JOHN SMITH'S PROFILE --
DELETE FROM TABLE(
    SELECT C.INVESTMENTS
    FROM CLIENTS C
    WHERE C.NAME = 'John Smith'
) I
WHERE I.COMPANY.COMPANY = 'INFOSYS'
/

-- INSERT GM STOCK INTO JOHN SMITH'S PROFILE --
INSERT INTO TABLE(
    SELECT C.INVESTMENTS
    FROM CLIENTS C
    WHERE C.NAME = 'John Smith'
) I
VALUES(
    (SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'GM'),
    (SELECT S.CURR_PRICE FROM STOCKS S WHERE S.COMPANY = 'GM'),
    '11-SEP-2019',
    '500'
)
/

-- DELETE GM STOCKS FROM JIL BRODY'S PROFILE --
DELETE FROM TABLE(
    SELECT C.INVESTMENTS
    FROM CLIENTS C
    WHERE C.NAME = 'Jil Brody'
) I
WHERE I.COMPANY.COMPANY = 'GM'
/

-- INSERT INFOSYS STOCK INTO JIL BRODY'S PROFILE --
INSERT INTO TABLE(
    SELECT C.INVESTMENTS
    FROM CLIENTS C
    WHERE C.NAME = 'Jil Brody'
) I
VALUES(
    (SELECT REF(S) FROM STOCKS S WHERE S.COMPANY = 'INFOSYS'),
    (SELECT S.CURR_PRICE FROM STOCKS S WHERE S.COMPANY = 'INFOSYS'),
    '11-SEP-2019',
    '1000'
)
/

commit
/
